# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Silas Chang
author: Silas Chang
# logo: images/icon.png
copyright: ""

# Do not execute notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
